version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

additional_build_files:
    - src: ansible.cfg
      dest: configs

additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

dependencies:
  python_interpreter:
    package_system: "python3"

  python:
    - kubernetes
    - openshift
    - PyYAML

  galaxy:
    collections:
      - kubernetes.core
      - redhat.openshift
      - redhat.openshift_virtualization